---
title: Grading
---

## Final Grade Breakdown

| Percentage of Final Grade |  Individual Grade Contribution |
| :----- | :----- |
| 5  |    In-class participation |
| 5  |    Quizzes |
| 10  |   Homework Assignments |
| 25  | Midterm exam 1 |
| 25 | Midterm exam 2 |
| 30 | Final Project |

::: {.callout-important title="Late Homework Policy"}
All assignments will be accepted up to 2 calendar days late (cutoff 11:59 pm).

- Assignments turned in one day late will be penalized by 10%.
- Assignments turned in two days late will be penalized by 20%.
- After two calendar days, assignments will not be accepted, and you will receive a 0 on the assignment.

:::

::: {.callout-note}
The lowest homework score will be dropped.
:::


## Final Percentage Score to Letter Grade Conversion

| Final percentage Score |  Letter grade | 4.0 Scale |
| :----- | :----- | :----- |
| 93-100 | A | 4.0 |
| 90-92 | A- | 3.7 |
| 87-89 | B+ | 3.3 |
| 83-86 | B | 3.0 |
| 80-82 | B- | 2.7 |
| 77-79 | C+ | 2.3 |
| 73-76 | C | 2.0 |
| 70-72 | C- | 1.7 |
| 67-69 | D+ | 1.3 |
| 63-66 | D | 1.0 |
| 60-62 | D- | 0.7 |
| <60 | F | 0.0 |


## Midterm Exam Grading

The midterm exams will be graded on a curve such that the average score is a B. However, I will not truncate the high scores
which means that scores higher than 100% are possible. This way, *everyone benefits* from the grade curving process.

For the midterm letter grade, the same grade conversion applies as above, however scores greater or equal to 97 will receive
the **A+** grade (unlike for the final grade, where **A** is the highest grade at Northeastern University) and
67-69, 63-66, and 60-62 will receive **D+**, **D**, and **D-**, respectively (unlike for the final grade, where all these would be an **F**).

## Final Project Grading

See evaluation criteria on the [finals project page](final_project.html).
