---
title: Ph.D. Qualification Exam - Materials Concentration
---

MATL 7355 is a core course for the Ph.D. qualification exam in MIE for the materials concentration.

## Information for MSE Part I, *"Thermodynamics of Materials"*

The general topics covered for this exam align with the [syllabus](syllabus.html) of this course and are summarized in the list below.

- Three laws of thermodynamics
- State and path functions (exact and inexact differentials)
- Entropy and Clausius inequalities
- Thermodynamic potentials and Maxwell relations
- Thermochemistry calculations and Hess’s law
- Systems and processes (e.g., isothermal, isobaric…)
- Phase equilibria and stability
- Ideal and non-ideal gases
- Behavior of Solutions (Henry and Raoult’s laws, Hume-Rothery rules)
- Phase diagrams (single-component and binary systems)
- Statistical thermodynamics (entropy, heat capacity, micro/macrostates, partition function)

However, each year specific topics may be excluded from the exams (see next section below).

::: {.callout-important title="Number of Questions"}
MSE Part I will contain *three questions*. Students are asked to solve all three.

The problem in which the lowest score will contribute 20% to the final grade while the other two problems will contribute 40% each.
:::

::: {.callout-important title="Notes Policy"}
For MSE Part I, one letter page (8.5" x 11") of notes (both sides) is allowed. No other resources/notes will be allowed (except for a calculator).
:::

::: {.callout-note}
Questions in MSE Part I may have sub-questions (a, b, c,...) and will be of similar style to the homework and mid-term exam
(however, will be *unique* and not be an old question with different numbers).
:::

::: {.callout-note}
Formula sheet will **not** be provided in this exam. However, all questions of MSE Part I will state the key equations and constants
needed to solve the problem.
:::

### Additional Details for the 2025 Exam

The points below only apply to the exam held in 2025 and may slightly change in future years.

1. The following topics will **not** be asked:

    - Open systems
    - Systems with magnetic/electric fields
    - Statistical Thermodynamics
    - Einstein/Debye models of heat capacity
    - Non-ideal gases and Van de Waals Gas calculations
    - Subregular solutions
    - Gibbs-Duhem integration
    - Ternary phase diagrams

2. **One question of MSE Part I will be on binary phase diagrams.** So, make sure you understand them well.


::: {.callout-note}
For information on MSE Part II, *"Kinetics of Phase Transformations"*, please contact Prof. Upmanyu.
:::

