---
title: Syllabus
---

The course syllabus below is a general outline of the course's content but is subject to small changes
depending on student's interest and pace.

| Week/Date | Topic | Homework Due |
| :--- | :--- | :--- |
| Week 1/Day 1  | Introduction and history of thermodynamics |  |
| Week 2/Day 1  | Basic concepts and history of the first law |  |
| Week 2/Day 2  | First law of thermodynamics |  |
| Week 3/Day 1  | Second law of thermodynamics | HW1 |
| Week 3/Day 2  | Fundamental thermodynamic relations/equations |  |
| Week 4/Day 1  | Statistical interpretation of the second law | HW2 |
| Week 4/Day 2  | Heat Capacity and Thermochemistry |  |
| Week 5/Day 1  | The third law of thermodynamics | HW3 |
| Week 5/Day 2  | Phase equilibria I: One-component systems |  |
| Week 6/Day 1  | Phase equilibria I: One-component systems | HW4 |
| Week 6/Day 2  | Review session for mid-term exam 1 |  |
| Week 7/Day 1  | **Mid-term exam 1** (in-class)  |  |
| Week 7/Day 2  | Thermodynamics of pure substances |  |
| Week 8/Day 1  | Thermodynamics of solutions | HW5 |
| Week 8/Day 2  | Thermodynamics of solutions |  |
| Week 9/Day 1  | Thermodynamics of solutions |  |
| Week 9/Day 2  | Phase equilibria II: Two-component systems |  |
| Week 10/Day 1 | Phase equilibria II: Two-component systems | HW6 |
| Week 10/Day 2 | Phase equilibria II: Two-component systems |  |
| Week 11/Day 1 | *Advanced Topic* | HW7 |
| Week 11/Day 2 | Review session for mid-term exam 2 |  |
| Week 12/Day 1 | **Mid-term exam 2** (in-class) |  |
| Week 12/Day 2 | *Advanced Topic* |  |
| Week 13/Day 1 | *Advanced Topic* |  |
| Week 13/Day 2 | Thanksgiving recess (no class) |  |
| Week 14/Day 1 | **Final project presentations** (in-class) | HW8 |
| Week 14/Day 2 | **Final project presentations** (in-class) |  |
| Week 15/Day 1 | **Final project presentations** (in-class) |  |

**Advanced Topics**: Ternary Phase diagrams, predominance phase diagrams, electrochemistry,
statistical thermodynamics & molecular dynamics, phase transformations, condensed - gaseous phase reactions,...

::: {.callout-note}
Homework due dates and Thanksgiving recess are estimates and may vary year to year
:::
